#!/bin/bash

function echo_colored {
  local color_code="$1"
  local message="$2"
  echo -e "\033[${color_code}m${message}\033[0m"
}

OUTPUT_FILE=${1:-"CHANGELOG.md"}
BRANCH=${2:-"main"}

echo_colored "34" "[INFO] Get changes from branch: $BRANCH."
CHANGES=$(git log "${BRANCH}" --pretty=format:"- %s" --no-merges --abbrev-commit)

if [ -z "$CHANGES" ]; then
  echo_colored "33" "[WARNING] No changes found. File $OUTPUT_FILE not generated."
  exit 0
fi

{
  echo "# Changelog"
  echo
  echo "## Changes (commit msg):"
  echo
  echo "$CHANGES"
} > "$OUTPUT_FILE"

if [ $? -eq 0 ]; then
  echo_colored "32" "[SUCCESS] File $OUTPUT_FILE created."
else
  echo_colored "31" "[ERROR] Error while creating file $OUTPUT_FILE."
  exit 1
fi

