name: Build and Release

on:
  push:
    tags:
      - 'v*'
jobs:
  build:
    runs-on: ubuntu-24.04

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.23.4'

    - name: Install dependencies (if needed)
      working-directory: ./app
      run: |
        ls -lah 
        pwd
        go mod tidy

    - name: Build binaries
      working-directory: app
      run: |
        GOOS=linux GOARCH=amd64 go build -o ManifestScriptor
        GOOS=windows GOARCH=amd64 go build -o ManifestScriptor.exe
        GOOS=darwin GOARCH=amd64 go build -o ManifestScriptor.app

    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: ManifestScriptor
        path: |
          app/ManifestScriptor
          app/ManifestScriptor.exe
          app/ManifestScriptor.app

  release:
    needs: build
    runs-on: ubuntu-24.04
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
        ref: main
    - name: Generate Changelog
      run: .github/workflows/generator ${{ github.workspace }}-CHANGELOG.md main
    - name: Create GitHub release
      uses: softprops/action-gh-release@v2
      if: startsWith(github.ref, 'refs/tags/')  
      with:
        body_path: ${{ github.workspace }}-CHANGELOG.md
        files: |
          app/ManifestScriptor
          app/ManifestScriptor.exe
          app/ManifestScriptor.app
      env:
        GITHUB_TOKEN: ${{ secrets.REALESE_KEY }}

