name: Build and Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.23.4'

    - name: Install dependencies (if needed)
      working-directory: ./app
      run: |
        go mod tidy

    - name: Build binaries
      working-directory: app
      run: |
        GOOS=linux GOARCH=amd64 go build -o ManifestScriptor
        GOOS=windows GOARCH=amd64 go build -o ManifestScriptor.exe
        GOOS=darwin GOARCH=amd64 go build -o ManifestScriptor.app

    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: ManifestScriptor
        path: |
          ManifestScriptor
          ManifestScriptor.exe
          ManifestScriptor.app

  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Create GitHub release
      uses: softprops/action-gh-release@v2
      with:
        files: |
          ManifestScriptor
          ManifestScriptor.exe
          ManifestScriptor.app

      env:
        GITHUB_TOKEN: ${{ secrets.REALESE_KEY }}

